# Copy file to planeur.net FTP server

name: 1 - Create .cupx

# Controls when the workflow will run
on:
  # Triggers the workflow After the version has been added
  workflow_run:
    workflows: ["1 - Add version to guide_aires_securite.cup"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# see: https://github.com/marketplace/actions/ftp-deployment
jobs:
  convert-to-cupx:
    name: Convert guide_aires_securite.cup to .cupx
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3

    - name: âš™ï¸ Convert to .cup to .cupx and push to repo
      run: |
        echo "Creating new .cupx file"
        zip points.zip guide_aires_securite.cup
        zip -r pics.zip Pics
        cat pics.zip points.zip > guide_aires_securite.cupx
        
        # push to repo
        echo "Pulling latest version before push..."
        git pull

    - name: âš™ï¸ Push .cub to repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        file_pattern: 'guide_aires_securite.cupx'


